package com.github.seanspace.dao.user;

import com.github.seanspace.entity.user.User;
import com.github.seanspace.entity.user.UserParam;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Dec 17 23:39:26 CST 2017
     */
    int countByExample(UserParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Dec 17 23:39:26 CST 2017
     */
    int deleteByExample(UserParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Dec 17 23:39:26 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Dec 17 23:39:26 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Dec 17 23:39:26 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Dec 17 23:39:26 CST 2017
     */
    List<User> selectByExample(UserParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Dec 17 23:39:26 CST 2017
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Dec 17 23:39:26 CST 2017
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Dec 17 23:39:26 CST 2017
     */
    int updateByExample(@Param("record") User record, @Param("example") UserParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Dec 17 23:39:26 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Dec 17 23:39:26 CST 2017
     */
    int updateByPrimaryKey(User record);
}